# Generated by Django 3.1.1 on 2021-02-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabExam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_date', models.DateField()),
                ('exam_name', models.CharField(max_length=200)),
                ('exam_description', models.TextField()),
                ('total_marks', models.FloatField()),
                ('pass_marks', models.FloatField()),
                ('exam_status', models.BooleanField()),
            ],
        ),
    ]
